spring.application.name=Transpera

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Transpera
spring.datasource.username=postgres
spring.datasource.password=Puneet@12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect